# docker-compose.yml
version: '3'
services:

  db:
    image: postgres:17.0-alpine
    environment:
      POSTGRES_USER: spider
      POSTGRES_PASSWORD: ZNCyCNc2rQ7kDN3n
      POSTGRES_DB: spider
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: